version: '3.9'
services:
  bot:
    image: instakot
    build: ./bot/
    #command: python3 bot.py
    volumes:
      - ./bot:/bot
      - ./downloads:/bot/downloads
      - ./logs:/bot/logs
    env_file: .env
    # depends_on:
    #   - db_kot
    networks:
      - default
      - db-net
  # db_kot:
  #   container_name: db_kot
  #   image: postgres
  #   command:
  #     - "postgres"
  #     - "-c"
  #     - "max_connections=50"
  #     - "-c"
  #     - "shared_buffers=1GB"
  #     - "-c"
  #     - "effective_cache_size=4GB"
  #     - "-c"
  #     - "work_mem=16MB"
  #     - "-c"
  #     - "maintenance_work_mem=512MB"
  #     - "-c"
  #     - "random_page_cost=1.1"
  #     - "-c"
  #     - "temp_file_limit=10GB"
  #     - "-c"
  #     - "log_min_duration_statement=200ms"
  #     - "-c"
  #     - "idle_in_transaction_session_timeout=10s"
  #     - "-c"
  #     - "lock_timeout=1s"
  #     - "-c"
  #     - "statement_timeout=60s"
  #     - "-c"
  #     - "shared_preload_libraries=pg_stat_statements"
  #     - "-c"
  #     - "pg_stat_statements.max=10000"
  #     - "-c"
  #     - "pg_stat_statements.track=all"
  #   env_file: .env
  #   restart: always
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 4G
    networks:
      - db-net
networks:
  default:
    driver: bridge
  db-net:
    external:
      name: db-net